name: Testnet deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M')"

      - name: Get the current version ref
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build
        env:
          CI: false
          VITE_API_URL: ${{ secrets.API_URL }}
          VITE_DONATION_ADDRESS: ${{ secrets.DONATION_ADDRESS }}
          VITE_NETWORK: mumbai
          VITE_FARM_MINTER_CONTRACT: "0x40748A2fC5D27Bf393EF6e73Fbc66d41bDC8C5bA"
          VITE_SESSION_CONTRACT: "0x4b60cB42d20Ed139f58733873F8d99B5834faCd3"
          VITE_FARM_CONTRACT: "0xbe606fC66DCD684A65352245C9e64323fae80b2E"
          VITE_INVENTORY_CONTRACT: "0xA0643dDDbaDf11ca201F6fBba55852960A50A8b2"
          VITE_TOKEN_CONTRACT: "0x2c597768BDff675660Ef1C4a16DfD2a34425DF22"
          VITE_WISHING_WELL_CONTRACT: "0x2a0fA94A095bAE0722B37f43B8A6becD85B9cCf2"
          VITE_PAIR_CONTRACT: "0xaE42EA9864C36820627068a11959915f817ce809"
          VITE_MOM_CONTRACT: "0x2cFdb89954991b69D6D4B2ec8b70f3b995F4E8Ec"
          VITE_TRADER_CONTRACT: "0x66e8429dE30D973d4E1E090620ccD5BeC8B31806"
          VITE_TREASURY_ADDRESS: "0x1DB57407EE80709D4d862fe81399FBB35B8B9586"
          VITE_BUMPKIN_MINTER_CONTRACT: "0xd775dB2F16915BdCF8f92A42786282F5F78Ad46E"
          VITE_BUMPKIN_DETAILS_CONTRACT: "0xcD48b039A6D1b5F9F2F381E7A0fFC243AD4767ef"
          VITE_DISCORD_REDIRECT: "https://sunflower-land.com/testnet/"
          VITE_CLIENT_VERSION: ${{ steps.date.outputs.date }}
          VITE_RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
          VITE_RECAPTCHA_SITEKEY: "6Lfqm6MeAAAAAFS5a0vwAfTGUwnlNoHziyIlOl1s"
          VITE_FROG_CONTRACT: "0x52A5ddFF59E0A27a1cBA75c8045A434b7D296A6c"
          VITE_FROG_DONATION: "0x1AFad0B5A0D532c9123A5f2F879A421413B5b6f7"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.9
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://sunflower-land.com/testnet --delete

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://www.sunflower-land.com/testnet --delete
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
